name: Upload files to release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 12 * *'


env:
  Manual_PUSH: true

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      # 获取latest release tag，cut切割无关内容。和仓库中LocalReleaseTag对比，之后输出tag给之后的步骤
      - name: Download Acidanthera && Hackintosh Tools
        id: download
        run: |
          chmod +x download.sh && bash download.sh
          OpenCorePkg_TAG=$(wget --no-check-certificate -qO- https://api.github.com/repos/acidanthera/OpenCorePkg/tags | grep 'name' | cut -d\" -f4 | head -1 )
          echo "::set-output name=version::${OpenCorePkg_TAG}"

      - name: Zip archiving
        id: archiving
        run: |
          zip -q -r all-files.zip ./*.zip
          zip -q -r Core-Components.zip ./Components
          zip -q -r Core-EFI.zip ./EFI

      - name: Upload files to release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Hackintosh Tools
          tag_name: ${{ steps.download.outputs.version }}
          body_path: ReleaseNote.md
          files: |
            ./*.zip

      # 判断是否需要PUSH，防止手动构建时报错      
      - name: Set Version
        id: set-version
        run: |
          TAG=$(wget --no-check-certificate -qO- https://api.github.com/repos/acidanthera/OpenCorePkg/tags | grep 'name' | cut -d\" -f4 | head -1 )

          OnlineReleaseTag=${TAG}
          LocalReleaseTag=$(cat ReleaseTag | head -n1)

          echo "LocalReleaseTag=$(cat ReleaseTag | head -n1)"
          echo "OnlineReleaseTag=${TAG}"

          if [ "${LocalReleaseTag}" != "${OnlineReleaseTag}" ]
          then
             echo "::set-output name=version::${TAG}"
             echo "::set-output name=status::success"
          fi

      # 将latest release tag写入到./ReleaseTag
      - name: Update ReleaseTag
        if: steps.set-version.outputs.status == 'success'
        run: |
          echo ${{ steps.set-version.outputs.version }} > ./ReleaseTag

      # push到GitHub的项目当中
      - name: Push
        if: steps.set-version.outputs.status == 'success' || env.Manual_PUSH == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "README.md && ReleaseNote.md"
          git push -v --progress
